# Generated by Django 3.1.4 on 2021-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('system_brand', models.CharField(max_length=10)),
                ('system_type', models.CharField(max_length=10)),
                ('system_model', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
