# Generated by Django 3.1.4 on 2021-05-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkstation', '0002_auto_20210524_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstation',
            old_name='username',
            new_name='system_user',
        ),
    ]
