# Generated by Django 3.1.4 on 2021-05-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkstation', '0003_auto_20210524_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstation',
            old_name='system_name',
            new_name='hostname',
        ),
    ]
