# Generated by Django 3.1.4 on 2021-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wkstation', '0004_auto_20210524_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
